# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Daemaged.IBNet/Daemaged.IBNet.csproj'
    arguments: '-c release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    searchPatternPack: 'Daemaged.IBNet/Daemaged.IBNet.csproj'
    configurationToPack: 'release'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'nupkg'

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    nuGetFeedType: 'external'
    externalEndpoint: '4508265b-628d-4848-b290-dee0316c76f5'